{"uuid": "c9d553b2-d60f-4289-bdc6-7b586d82356a", "children": ["06ad1055-a540-45ef-8926-f15151ae0d7f"], "befores": [{"name": "event_loop", "status": "passed", "start": 1741583696380, "stop": 1741583696382}], "afters": [{"name": "event_loop::3", "status": "broken", "statusDetails": {"message": "RuntimeError: Cannot close a running event loop\n", "trace": "  File \"C:\\Users\\ASTRID\\Test-frontend-QA-Cod\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ASTRID\\Test-frontend-QA-Cod\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"C:\\Users\\ASTRID\\Test-frontend-QA-Cod\\venv\\Lib\\site-packages\\pytest_asyncio\\plugin.py\", line 1151, in event_loop\n    with _temporary_event_loop_policy(new_loop_policy), _provide_event_loop() as loop:\n         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ASTRID\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\contextlib.py\", line 148, in __exit__\n    next(self.gen)\n    ~~~~^^^^^^^^^^\n  File \"C:\\Users\\ASTRID\\Test-frontend-QA-Cod\\venv\\Lib\\site-packages\\pytest_asyncio\\plugin.py\", line 776, in _temporary_event_loop_policy\n    current_loop.close()\n    ~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\ASTRID\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\asyncio\\proactor_events.py\", line 684, in close\n    raise RuntimeError(\"Cannot close a running event loop\")\n"}, "start": 1741583696452, "stop": 1741583696457}, {"name": "event_loop::_close_event_loop", "status": "passed", "start": 1741583696457, "stop": 1741583696457}, {"name": "event_loop::_restore_policy", "status": "passed", "start": 1741583696457, "stop": 1741583696457}, {"name": "event_loop::_provide_clean_event_loop", "status": "passed", "start": 1741583696457, "stop": 1741583696457}], "start": 1741583696380, "stop": 1741583696457}